sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-540.pdf --upload --lsstdoc LDM-540.tex --env=travis --ltd-product ldm-540"
env:
  global:
    # LSST the Docs credentials
    - secure: "DAXwnrcKHeiFipOyEeQe0Me0gjVVD3+CmYs6N5+jHmBsGKuYV39atIV/yJV9s5lfPVosDkoR37IpnWnbyHl7+46gaxtowUVTuFOYDvelwBz/FVdnm8JBF6l57WfLaIHeo1j/dFVBmq5AgwXrvIgATcTP+NxGjiOkqcObENNIAfpXUODRkXvBL/pMRMiRKr7IP7kwwORdxnGKe7M8gIfC5SOQrVHNM3TY9V42bLE8/2Qu3Q1wWeZfMIVPLPbfI6mE1cwLqSMLha3XxHIsWXOUKvHs76o31W/neC0p06acL+TNNpQSvJa+dX9c3Id8d/uI1iZON64u35GW+NhKbHyyZggatVxKujRmgXuD+27aRX1cW4KyrmFY0y1BJfauq8exWTBG57uEuzRDxTCuzHYjLWhPOlLmIb5NjiHBGK11tpazs8+BTFRNnXmk+zzsZY9pteqhnuGgKRVvb2xboYRnwiqtVg3GDwMyvng7bJEkbgLveW0TFJPBcaMjAqacYBNsay5etz1f4fdOuDgOvrrtT202WzLC8s3LYWT9GZZttCdtYqkEzjCZj+bPWxHHzMlSMLRctgbtI9PO1Fgckm9GDMKmyDIpTNVnfJ4Hsoq8H0nqqz3+swBUpZPg9ynPXPWX7yqs4Lj4tGfMkzf7nkoy5waWxHh76v6sn3LIk4gM4DM="
    - secure: "GeiXuUR8YoQ228Vpe91sQ8uzS1hrp7weunG+wZXBQ5DdZKmGqeafhFFTSAVH4+sO9/Vxpyt7+rrfrK4OnQ57udPx3bYnAnGeAZFcBqBFN/sv4vb3NVijbaTCA1HANb9eGM/4ka3G+wByY149CqiB44H6OK9Q9hZCHY81uMzg0/4Q/WSNHCugp2laytPurjDXZDoEj35VtPfF8OnAcS/LNmuAxjvroENXQDVlr724HxCclcBOvHqr2hc64QveVKQsaWPj+9gTHX5IoBbstEDZPlKKWtGwqdE5pnnVPvI3yYpOraR2qY5VkUuBNJedcFSt3VUD8DFmleaaHJEZFc5lCjXW0ZVsjEupv3CBZ1yHfzhT1585qHvEbswa8Yjot0ruddQ4ur3RMhpv951JRQiVzM2SNbPhZvHpJInlENbnqTk9TkthNeJFN4N8qVE/We8AdoWNr8OGrCPZYZmysPBpNLh5LKYV+IHLRNiK6t5M6O4oAYVv/20NLorZhfVq2EERhGB9IDAv/zY+V9jTdbvMYFeI3/RsXec1jC8QytIpVdVwpEYNG5KIWc8hZ3FERBjhz5S3gis2pGuY8f7e5FrwccOdJiS7D6jpJWTKKo4c0CoIFiCJD1hfarp+CYjRl/kFDWtSsf5xHXc1OEIydRtb+a2hZAz3IAifNroSHKFUmH0="
